[build]
  functions = "netlify/functions"
  publish = "/"  # Change this if `index.html` is NOT inside `public/`

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
