[build]
  functions = "netlify/functions"  # ✅ Ensures Netlify knows where functions are
  publish = "public"  # ✅ Correct publish directory

[[redirects]]
  from = "/article/*"
  to = "/.netlify/functions/redirect"
  status = 200
