[build]
  functions = "netlify/functions"
  publish = "."  # Ensures Netlify serves index.html

[[redirects]]
  from = "/article/*"
  to = "/.netlify/functions/redirect"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
