[build]
  functions = "netlify/functions"  # ✅ This tells Netlify where to find serverless functions
  publish = "/"  # ✅ This should be set correctly depending on your project structure

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
