[build]
  publish = "."

[[redirects]]
  from = "/article/:slug"
  to = "/article.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/get-article"
  to = "/.netlify/functions/get-article"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
